
FROM node:16.18.0-alpine as builder

COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./

RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
  else echo "Lockfile not found." && exit 1; \
  fi

RUN yarn install && mkdir /app && mv ./node_modules ./app

WORKDIR /app

COPY . .

RUN yarn build


